# db_playbook.yml
---
- name: Install and Configure Database Server
  hosts: dbservers
  become: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: latest

    - name: Ensure PostgreSQL service is started
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes

